# Generated by Django 4.1.1 on 2022-09-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_macadders_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
