# Generated by Django 4.1.1 on 2022-09-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_attendrecord_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attends', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='macadders',
            name='address',
            field=models.CharField(max_length=20),
        ),
    ]
