# Generated by Django 4.1.1 on 2022-09-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
    ]
